// src/pages/HomePage.jsx
import Landing from "../components/Landing";
import TechStack from "../components/TechStack";
import Projects from "../components/Projects";
import Contact from "../components/Contact";

const Home = () => {
  return (
    <>
      <Landing />
      <TechStack />
      <Projects />
      <Contact />
    </>
  );
}

export default Home;

// devfolio-vue/src/pages/HomePage.vue
<template>

  <Landing />
  <Projects />
  <Tools />

</template>

<script setup>
import Landing from '../components/Landing.vue'
import Projects from '../components/Projects.vue'
import Tools from '../components/Tools.vue'
import { useDarkMode } from '../composables/theme.js'

const { isDark, toggleTheme } = useDarkMode()

</script>
